# Generated by Django 5.1.4 on 2024-12-21 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, help_text='Укажите кол-во просмотров', verbose_name='Счетчик просмотров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Цена за продукт'),
        ),
    ]
