# Generated by Django 5.1.4 on 2025-02-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_views_counter_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views_counter',
        ),
    ]
